Algoritmo "verdadeiro&falso"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/01/2024
Var
// Seção de Declarações das variáveis 
   A, B, C: Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   A <- 2
   B <- 3
   C <- 5
   Escreva ((A/B=C) ou (C^A=B))

Fimalgoritmo